---
application_name: 'sorcery'
namespace: 'github.com/nicholasjackson'
generator_name: minke-generator-go
docker_registry:
  url: <%= ENV['DOCKER_REGISTRY_URL'] %>
  user: <%= ENV['DOCKER_REGISTRY_USER'] %>
  password: <%= ENV['DOCKER_REGISTRY_PASS'] %>
  email: <%= ENV['DOCKER_REGISTRY_EMAIL'] %>
  namespace: <%= ENV['DOCKER_NAMESPACE'] %>
docker:
  build_image: 'nicholasjackson/minke-generator-go'
  application_docker_file: './dockerfile/sorcery/'
  application_compose_file: './dockercompose/sorcery/docker-compose.yml'
fetch:
  enabled: true
test:
  enabled: true
build:
  post:
    copy:
      -
        from: '../sorcery'
        to: './dockerfile/sorcery'
      -
        from: './swagger_spec/swagger.yml'
        to: './dockerfile/sorcery/swagger_spec'
run:
  consul_loader:
    config_file: './consul_keys.yml'
    url:
      address: consul
      port: 8500
      type: bridge
cucumber:
  consul_loader:
    config_file: './consul_keys.yml'
    url:
      address: consul
      port: 8500
      type: bridge
  health_check:
    address: sorcery
    port: 8001
    path: /v1/health
    type: bridge
