engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
        - go
