swagger: '2.0'
info:
  title: Event Sauce API
  description: Event Sauce is a simple Event Sourcing system, the API allows the registration of consumers for events and also allows clients to send an event which is then dispatched to the registered consumers.
  version: 1.0.0
host: api.test.com
schemes:
  - http
  - https
basePath: /v1
produces:
  - application/json
paths:
  /health:
    get:
      summary: Health Check
      description: |
        The Health Check endpoint is used to determine the current status for the health of the api.
        This endpoint will be used by other systems such as Consul and other service discovery systems.
      tags:
        - Health
      responses:
        '200':
          description: Status message from server describing current health
          schema:
            type: object
            $ref: '#/definitions/Response'
  /register:
    post:
      summary: Register Consumer
      description: |
        The register endpoint allows consumers to register with the event store.
      tags:
        - Register
      parameters:
        - name: RegistrationRequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/RegistrationRequest'
      responses:
        '200':
          description: Successfull registration of a consumer
          schema:
            type: object
            $ref: '#/definitions/Response'
        '400':
          description: Bad request, possible invalid request object
        '304':
          description: Registration already exists
    delete:
      summary: Remove Consumer
      description: |
        The register endpoint allows consumers to remove subscriptions from the event store.
      tags:
        - Register
      parameters:
        - name: RegistrationRequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/RegistrationRequest'
      responses:
        '200':
          description: Successfull removal
          schema:
            type: object
            $ref: '#/definitions/Response'
        '400':
          description: Bad request, possible invalid request object
        '404':
          description: Registration does not exist
  /event:
    post:
      summary: Add a event to the queue
      description: |
        The event endpoint allows messages to be added to the event store, when a message is received it will be queued for dispatch to any consumers.
      tags:
        - Event
      parameters:
        - name: EventRequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/EventRequest'
      responses:
        '200':
          description: Successfull receipt of an event
          schema:
            type: object
            $ref: '#/definitions/Response'
        '400':
          description: Bad request, possible invalid request object
definitions:
  Response:
    type: object
    properties:
      status_message:
        type: string
        description: 'Plain text readable response'
  RegistrationRequest:
    type: object
    required:
      - message_name
      - callback_url
    properties:
      message:
        type: string
        description: 'The name of the message to subscibe updates to'
      callback_url:
        type: string
        description: 'Callback Url that the server will POST the message to'
  EventRequest:
    type: object
    required:
      - message_name
      - payload
    properties:
      message_name:
        type: string
        description: 'The name of the event'
      payload:
        type: string
        description: 'Payload for the message represented as a string'
