sorcery:
  image: sorcery
  ports:
    - "8001:8001"
  environment:
    - "CONSUL=consul:8500"
  links:
    - consul:consul
    - statsd:statsd
    - mongo:mongo
    - redis:redis
    - callbackserver:callbackserver
consul:
  image: 'progrium/consul:latest'
  ports:
    - "9400:8400"
    - "9500:8500"
    - "9600:53/udp"
  hostname: node1
  command: "-server -bootstrap -ui-dir /ui"
data:
  image: 'busybox:latest'
  volumes:
    - /data/db
  command: tail -f /dev/null
mongo:
  image: 'mongo:latest'
  ports:
    - '27017:27017'
  volumes_from:
    - data
  environment:
    - "SERVICE_27017_NAME=mongo-27017"
redis:
  image: 'redis:latest'
  ports:
    - '6380:6380'
    - '6379:6379'
statsd:
  image: 'hopsoft/graphite-statsd:latest'
  ports:
    - "8180:80"
    - "2003:2003"
    - "8125:8125/udp"
    - "8126:8126"
  environment:
    - "SERVICE_8125_NAME=statsd-8125"
callbackserver:
  image: nicholasjackson/mimic-docker
  ports:
    - "11988:11988"
registrator:
  command: -internal -tags=dev consul://consul:8500
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul
