---
namespace: 'github.com/nicholasjackson'
application_name: 'sorcery'
language: go
docker_registry:
  url: <%= ENV['DOCKER_REGISTRY_URL'] %>
  user: <%= ENV['DOCKER_REGISTRY_USER'] %>
  password: <%= ENV['DOCKER_REGISTRY_PASS'] %>
  email: <%= ENV['DOCKER_REGISTRY_EMAIL'] %>
  namespace: <%= ENV['DOCKER_NAMESPACE'] %>
docker:
  docker_file: './dockerfile/sorcery/'
  compose_file: './dockercompose/sorcery/docker-compose.yml'
run:
  consul_loader:
    enabled: true
    config_file: './consul_keys.yml'
    url: <%= "http://#{ENV['DOCKER_IP']}:9500" %>
cucumber:
  consul_loader:
    enabled: true
    config_file: './consul_keys.yml'
    url: <%= "http://#{ENV['DOCKER_IP']}:9500" %>
  health_check:
    enabled: true
    url: <%= "http://#{ENV['DOCKER_IP']}:8001/v1/health" %>
after_build:
  copy_assets:
    -
      from: <%= "#{ENV['GOPATH']}/src/github.com/nicholasjackson/sorcery/sorcery" %>
      to: './dockerfile/sorcery'
    -
      from: './swagger_spec/swagger.yml'
      to: './dockerfile/sorcery/swagger_spec'
