---
go:
  namespace: 'github.com/nicholasjackson'
  application_name: 'event-sauce'
  comand: '/usr/local/go/bin/go'
docker_registry:
  url: <%= ENV['DOCKER_REGISTRY_URL'] %>
  user: <%= ENV['DOCKER_REGISTRY_USER'] %>
  pass: <%= ENV['DOCKER_REGISTRY_PASS'] %>
  email: <%= ENV['DOCKER_REGISTRY_EMAIL'] %>
  namespace: <%= ENV['DOCKER_NAMESPACE'] %>
docker:
  docker_file: './dockerfile/event-sauce/'
  compose_file: './dockercompose/event-sauce/docker-compose.yml'
  build_args:
    image: 'golang:latest'
    env:
      - 'CGO_ENABLED=0' # used for alpine linux static linking
    working_directory: '/go/src/github.com/nicholasjackson/event-sauce'
run:
  consul_loader:
    enabled: true
    config_file: './consul_keys.yml'
    url: <%= "http://#{ENV['DOCKER_IP']}:9500" %>
cucumber:
  consul_loader:
    enabled: true
    config_file: './config_keys.yml'
    url: <%= "http://#{ENV['DOCKER_IP']}:9500" %>
  health_check:
    enabled: true
    url: <%= "http://#{ENV['DOCKER_IP']}:8001/v1/health" %>
after_build:
  copy_assets:
    -
      from: <%= "#{ENV['GOPATH']}/src/github.com/nicholasjackson/event-sauce/event-sauce" %>
      to: './dockerfile/event-sauce'
    -
      from: './swagger_spec/swagger.yml'
      to: './dockerfile/event-sauce/swagger_spec'
