source 'http://rubygems.org'

gem "rake"
gem "cucumber", "~> 1.3.10"
gem "cucumber-rest-api"
gem 'cucumber-mailcatcher', '~> 0.12'
gem 'pickle-mongodb', '~> 0.5'
gem 'pry', '~> 0.10.3'
gem 'redis', '~>3.2'
gem 'rest-client', '~> 1.8'
gem 'go_builder', '~> 0.3.0'
